/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    media: Media;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    identity: Identity;
    theme: Theme;
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    identity: IdentitySelect<false> | IdentitySelect<true>;
    theme: ThemeSelect<false> | ThemeSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles?: ('owner' | 'admin' | 'editor')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Internal reference title for this page (e.g., "Home Page").
   */
  title: string;
  blocks: (
    | ContactFormData
    | CTAData
    | FAQData
    | FeaturesData
    | HeroData
    | LogosData
    | PricingData
    | StatsData
    | TestimonialsData
  )[];
  /**
   * The URL path. Use "home" for the root index (/).
   */
  slug?: string | null;
  seo?: {
    /**
     * The title tag shown in search engines and browser tabs.
     */
    title: string;
    /**
     * The meta description shown in search engine results.
     */
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactFormData".
 */
export interface ContactFormData {
  /**
   * Optional. Define a unique ID for this block to enable deep-linking (e.g., entering "services" here allows linking to "#services"). Do not include the # symbol.
   */
  anchorId?: string | null;
  /**
   * Choose contact form layout.
   */
  variant: 'split' | 'card' | 'minimal';
  badge?: {
    label?: string | null;
    color?: ('primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error') | null;
    size?: ('xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    isOutline?: boolean | null;
  };
  heading: string;
  subheading?: string | null;
  showContactDetails?: boolean | null;
  detailsHeading?: string | null;
  emailLabel?: string | null;
  email?: string | null;
  phoneLabel?: string | null;
  phone?: string | null;
  addressLabel?: string | null;
  address?: string | null;
  formTitle: string;
  nameLabel: string;
  emailFieldLabel: string;
  messageLabel: string;
  includeCompanyField?: boolean | null;
  companyFieldLabel?: string | null;
  includePhoneField?: boolean | null;
  phoneFieldLabel?: string | null;
  includeSubjectField?: boolean | null;
  subjectFieldLabel?: string | null;
  submitLabel: string;
  consentText?: string | null;
  successMessage: string;
  errorMessage: string;
  /**
   * Advanced: endpoint that handles form submissions.
   */
  endpoint: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contact-form';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTAData".
 */
export interface CTAData {
  /**
   * Optional. Define a unique ID for this block to enable deep-linking (e.g., entering "services" here allows linking to "#services"). Do not include the # symbol.
   */
  anchorId?: string | null;
  /**
   * Choose CTA presentation. Field visibility updates to match this layout.
   */
  variant: 'banner' | 'card' | 'split-panel';
  badge?: {
    label?: string | null;
    color?: ('primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error') | null;
    size?: ('xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    isOutline?: boolean | null;
  };
  heading: string;
  subheading?: string | null;
  primaryAction: {
    label: string;
    url: string;
    target?: ('_self' | '_blank') | null;
    style?: ('primary' | 'secondary' | 'accent' | 'neutral' | 'ghost' | 'outline' | 'link') | null;
    size?: ('sm' | 'md' | 'lg') | null;
  };
  secondaryAction: {
    label: string;
    url: string;
    target?: ('_self' | '_blank') | null;
    style?: ('primary' | 'secondary' | 'accent' | 'neutral' | 'ghost' | 'outline' | 'link') | null;
    size?: ('sm' | 'md' | 'lg') | null;
  };
  finePrint?: string | null;
  backgroundImage?: (number | null) | Media;
  panelTitle?: string | null;
  panelItems?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Screen reader text. Crucial for SEO and Accessibility.
   */
  altText: string;
  /**
   * Optional base64 blurhash string for instant loading states.
   */
  blurhash?: string | null;
  /**
   * Object-position X percentage (0-100)
   */
  focalPointX?: number | null;
  /**
   * Object-position Y percentage (0-100)
   */
  focalPointY?: number | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    logo?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    avatar?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQData".
 */
export interface FAQData {
  /**
   * Optional. Define a unique ID for this block to enable deep-linking (e.g., entering "services" here allows linking to "#services"). Do not include the # symbol.
   */
  anchorId?: string | null;
  /**
   * Choose FAQ layout.
   */
  variant: 'accordion' | 'list' | 'two-column';
  heading: string;
  subheading?: string | null;
  /**
   * Enable to allow multiple expanded items at once in accordion mode.
   */
  allowMultipleOpen?: boolean | null;
  items: {
    question: string;
    answer: string;
    isOpenByDefault?: boolean | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturesData".
 */
export interface FeaturesData {
  /**
   * Optional. Define a unique ID for this block to enable deep-linking (e.g., entering "services" here allows linking to "#services"). Do not include the # symbol.
   */
  anchorId?: string | null;
  /**
   * Choose the Features layout. Fields below adapt to the selected variant.
   */
  variant: 'grid' | 'list' | 'spotlight';
  badge?: {
    label?: string | null;
    color?: ('primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error') | null;
    size?: ('xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    isOutline?: boolean | null;
  };
  heading: string;
  subheading?: string | null;
  columns?: ('2' | '3' | '4') | null;
  spotlightMedia?: (number | null) | Media;
  spotlightMediaPosition?: ('left' | 'right') | null;
  features: {
    title: string;
    description: string;
    icon: {
      type?: ('lucide' | 'svg-string' | 'image') | null;
      /**
       * Enter the Lucide icon name, paste raw SVG, or provide an image URL based on the type selected.
       */
      value: string;
    };
    action?: {
      label?: string | null;
      url?: string | null;
      target?: ('_self' | '_blank') | null;
      style?: ('primary' | 'secondary' | 'accent' | 'neutral' | 'ghost' | 'outline' | 'link') | null;
      size?: ('sm' | 'md' | 'lg') | null;
    };
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'features';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroData".
 */
export interface HeroData {
  /**
   * Optional. Define a unique ID for this block to enable deep-linking (e.g., entering "services" here allows linking to "#services"). Do not include the # symbol.
   */
  anchorId?: string | null;
  /**
   * Choose a hero layout. Field visibility below adapts to the selected variant.
   */
  variant: 'split' | 'centered' | 'cinematic' | 'diagonal-split';
  badge?: {
    label?: string | null;
    color?: ('primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error') | null;
    size?: ('xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    isOutline?: boolean | null;
  };
  headline: string;
  subheading: string;
  primaryAction: {
    label: string;
    url: string;
    target?: ('_self' | '_blank') | null;
    style?: ('primary' | 'secondary' | 'accent' | 'neutral' | 'ghost' | 'outline' | 'link') | null;
    size?: ('sm' | 'md' | 'lg') | null;
  };
  secondaryAction: {
    label: string;
    url: string;
    target?: ('_self' | '_blank') | null;
    style?: ('primary' | 'secondary' | 'accent' | 'neutral' | 'ghost' | 'outline' | 'link') | null;
    size?: ('sm' | 'md' | 'lg') | null;
  };
  highlights?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  media?: (number | null) | Media;
  mediaPosition?: ('left' | 'right') | null;
  backgroundImage?: (number | null) | Media;
  panelEyebrow?: string | null;
  panelStatusText?: string | null;
  /**
   * Auto detects image brightness behind the content area. Use manual tone when art direction requires it.
   */
  cinematicToneMode?: ('auto' | 'light' | 'dark') | null;
  diagonalAccentLabel?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogosData".
 */
export interface LogosData {
  /**
   * Optional. Define a unique ID for this block to enable deep-linking (e.g., entering "services" here allows linking to "#services"). Do not include the # symbol.
   */
  anchorId?: string | null;
  /**
   * Choose logo layout. Available options adapt to the selected variant.
   */
  variant: 'grid' | 'strip' | 'monochrome';
  heading: string;
  subheading?: string | null;
  columns?: ('3' | '4' | '5' | '6') | null;
  stripItemWidth?: ('sm' | 'md' | 'lg') | null;
  logos: {
    media: number | Media;
    url?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'logos';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingData".
 */
export interface PricingData {
  /**
   * Optional. Define a unique ID for this block to enable deep-linking (e.g., entering "services" here allows linking to "#services"). Do not include the # symbol.
   */
  anchorId?: string | null;
  /**
   * Choose pricing presentation. The section adapts to this variant.
   */
  variant: 'cards' | 'comparison' | 'compact';
  badge?: {
    label?: string | null;
    color?: ('primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error') | null;
    size?: ('xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    isOutline?: boolean | null;
  };
  heading: string;
  subheading?: string | null;
  billingNote?: string | null;
  comparisonFootnote?: string | null;
  compactEyebrow?: string | null;
  plans: {
    name: string;
    price: string;
    billingPeriod?: string | null;
    description?: string | null;
    planBadge?: string | null;
    isHighlighted?: boolean | null;
    features: {
      item: string;
      /**
       * Use this to mark excluded items in Comparison mode.
       */
      included?: boolean | null;
      id?: string | null;
    }[];
    action: {
      label: string;
      url: string;
      target?: ('_self' | '_blank') | null;
      style?: ('primary' | 'secondary' | 'accent' | 'neutral' | 'ghost' | 'outline' | 'link') | null;
      size?: ('sm' | 'md' | 'lg') | null;
    };
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'pricing';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsData".
 */
export interface StatsData {
  /**
   * Optional. Define a unique ID for this block to enable deep-linking (e.g., entering "services" here allows linking to "#services"). Do not include the # symbol.
   */
  anchorId?: string | null;
  /**
   * Choose the stats presentation style.
   */
  variant: 'band' | 'grid' | 'spotlight';
  heading?: string | null;
  subheading?: string | null;
  spotlightLabel?: string | null;
  items: {
    label: string;
    value: string;
    description?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsData".
 */
export interface TestimonialsData {
  /**
   * Optional. Define a unique ID for this block to enable deep-linking (e.g., entering "services" here allows linking to "#services"). Do not include the # symbol.
   */
  anchorId?: string | null;
  /**
   * Choose how testimonials are presented.
   */
  variant: 'grid' | 'featured' | 'stacked';
  badge?: {
    label?: string | null;
    color?: ('primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error') | null;
    size?: ('xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    isOutline?: boolean | null;
  };
  heading: string;
  subheading?: string | null;
  featuredEyebrow?: string | null;
  testimonials: {
    quote: string;
    authorName: string;
    authorRole?: string | null;
    authorCompany?: string | null;
    authorImage?: (number | null) | Media;
    rating?: number | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  submittedAt: string;
  status: 'new' | 'in-progress' | 'resolved';
  name: string;
  email: string;
  company?: string | null;
  phone?: string | null;
  subject?: string | null;
  message: string;
  variant?: string | null;
  blockId?: string | null;
  consentAccepted?: boolean | null;
  source?: {
    pagePath?: string | null;
    pageUrl?: string | null;
    referrer?: string | null;
    userAgent?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  blocks?:
    | T
    | {
        'contact-form'?: T | ContactFormDataSelect<T>;
        cta?: T | CTADataSelect<T>;
        faq?: T | FAQDataSelect<T>;
        features?: T | FeaturesDataSelect<T>;
        hero?: T | HeroDataSelect<T>;
        logos?: T | LogosDataSelect<T>;
        pricing?: T | PricingDataSelect<T>;
        stats?: T | StatsDataSelect<T>;
        testimonials?: T | TestimonialsDataSelect<T>;
      };
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactFormData_select".
 */
export interface ContactFormDataSelect<T extends boolean = true> {
  anchorId?: T;
  variant?: T;
  badge?:
    | T
    | {
        label?: T;
        color?: T;
        size?: T;
        isOutline?: T;
      };
  heading?: T;
  subheading?: T;
  showContactDetails?: T;
  detailsHeading?: T;
  emailLabel?: T;
  email?: T;
  phoneLabel?: T;
  phone?: T;
  addressLabel?: T;
  address?: T;
  formTitle?: T;
  nameLabel?: T;
  emailFieldLabel?: T;
  messageLabel?: T;
  includeCompanyField?: T;
  companyFieldLabel?: T;
  includePhoneField?: T;
  phoneFieldLabel?: T;
  includeSubjectField?: T;
  subjectFieldLabel?: T;
  submitLabel?: T;
  consentText?: T;
  successMessage?: T;
  errorMessage?: T;
  endpoint?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTAData_select".
 */
export interface CTADataSelect<T extends boolean = true> {
  anchorId?: T;
  variant?: T;
  badge?:
    | T
    | {
        label?: T;
        color?: T;
        size?: T;
        isOutline?: T;
      };
  heading?: T;
  subheading?: T;
  primaryAction?:
    | T
    | {
        label?: T;
        url?: T;
        target?: T;
        style?: T;
        size?: T;
      };
  secondaryAction?:
    | T
    | {
        label?: T;
        url?: T;
        target?: T;
        style?: T;
        size?: T;
      };
  finePrint?: T;
  backgroundImage?: T;
  panelTitle?: T;
  panelItems?:
    | T
    | {
        item?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQData_select".
 */
export interface FAQDataSelect<T extends boolean = true> {
  anchorId?: T;
  variant?: T;
  heading?: T;
  subheading?: T;
  allowMultipleOpen?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        isOpenByDefault?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturesData_select".
 */
export interface FeaturesDataSelect<T extends boolean = true> {
  anchorId?: T;
  variant?: T;
  badge?:
    | T
    | {
        label?: T;
        color?: T;
        size?: T;
        isOutline?: T;
      };
  heading?: T;
  subheading?: T;
  columns?: T;
  spotlightMedia?: T;
  spotlightMediaPosition?: T;
  features?:
    | T
    | {
        title?: T;
        description?: T;
        icon?:
          | T
          | {
              type?: T;
              value?: T;
            };
        action?:
          | T
          | {
              label?: T;
              url?: T;
              target?: T;
              style?: T;
              size?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroData_select".
 */
export interface HeroDataSelect<T extends boolean = true> {
  anchorId?: T;
  variant?: T;
  badge?:
    | T
    | {
        label?: T;
        color?: T;
        size?: T;
        isOutline?: T;
      };
  headline?: T;
  subheading?: T;
  primaryAction?:
    | T
    | {
        label?: T;
        url?: T;
        target?: T;
        style?: T;
        size?: T;
      };
  secondaryAction?:
    | T
    | {
        label?: T;
        url?: T;
        target?: T;
        style?: T;
        size?: T;
      };
  highlights?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  media?: T;
  mediaPosition?: T;
  backgroundImage?: T;
  panelEyebrow?: T;
  panelStatusText?: T;
  cinematicToneMode?: T;
  diagonalAccentLabel?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogosData_select".
 */
export interface LogosDataSelect<T extends boolean = true> {
  anchorId?: T;
  variant?: T;
  heading?: T;
  subheading?: T;
  columns?: T;
  stripItemWidth?: T;
  logos?:
    | T
    | {
        media?: T;
        url?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingData_select".
 */
export interface PricingDataSelect<T extends boolean = true> {
  anchorId?: T;
  variant?: T;
  badge?:
    | T
    | {
        label?: T;
        color?: T;
        size?: T;
        isOutline?: T;
      };
  heading?: T;
  subheading?: T;
  billingNote?: T;
  comparisonFootnote?: T;
  compactEyebrow?: T;
  plans?:
    | T
    | {
        name?: T;
        price?: T;
        billingPeriod?: T;
        description?: T;
        planBadge?: T;
        isHighlighted?: T;
        features?:
          | T
          | {
              item?: T;
              included?: T;
              id?: T;
            };
        action?:
          | T
          | {
              label?: T;
              url?: T;
              target?: T;
              style?: T;
              size?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsData_select".
 */
export interface StatsDataSelect<T extends boolean = true> {
  anchorId?: T;
  variant?: T;
  heading?: T;
  subheading?: T;
  spotlightLabel?: T;
  items?:
    | T
    | {
        label?: T;
        value?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsData_select".
 */
export interface TestimonialsDataSelect<T extends boolean = true> {
  anchorId?: T;
  variant?: T;
  badge?:
    | T
    | {
        label?: T;
        color?: T;
        size?: T;
        isOutline?: T;
      };
  heading?: T;
  subheading?: T;
  featuredEyebrow?: T;
  testimonials?:
    | T
    | {
        quote?: T;
        authorName?: T;
        authorRole?: T;
        authorCompany?: T;
        authorImage?: T;
        rating?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  altText?: T;
  blurhash?: T;
  focalPointX?: T;
  focalPointY?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        logo?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        avatar?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  submittedAt?: T;
  status?: T;
  name?: T;
  email?: T;
  company?: T;
  phone?: T;
  subject?: T;
  message?: T;
  variant?: T;
  blockId?: T;
  consentAccepted?: T;
  source?:
    | T
    | {
        pagePath?: T;
        pageUrl?: T;
        referrer?: T;
        userAgent?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "identity".
 */
export interface Identity {
  id: number;
  siteName: string;
  logoLight?: (number | null) | Media;
  logoDark?: (number | null) | Media;
  favicon?: (number | null) | Media;
  /**
   * Choose the size of the text logo
   */
  logoSize?: ('xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme".
 */
export interface Theme {
  id: number;
  /**
   * The fallback DaisyUI theme for the entire website.
   */
  defaultTheme:
    | 'edgezero-light'
    | 'edgezero-dark'
    | 'light'
    | 'cupcake'
    | 'bumblebee'
    | 'emerald'
    | 'corporate'
    | 'retro'
    | 'cyberpunk'
    | 'valentine'
    | 'garden'
    | 'aqua'
    | 'lofi'
    | 'pastel'
    | 'fantasy'
    | 'wireframe'
    | 'cmyk'
    | 'autumn'
    | 'acid'
    | 'lemonade'
    | 'winter'
    | 'nord'
    | 'dark'
    | 'synthwave'
    | 'halloween'
    | 'forest'
    | 'black'
    | 'luxury'
    | 'dracula'
    | 'business'
    | 'night'
    | 'coffee'
    | 'dim'
    | 'sunset';
  fonts: {
    /**
     * Google Font name for standard text.
     */
    sans: string;
    /**
     * Google Font name for headings.
     */
    heading: string;
  };
  structure: {
    radiusBox: string;
    radiusField: string;
    radiusSelector: string;
    borderSize: string;
    depth?: ('0' | '1') | null;
    noise?: ('0' | '1') | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  isSticky?: boolean | null;
  /**
   * Optional DaisyUI theme name for the header (e.g., "dark")
   */
  themeOverride?: string | null;
  navigation?:
    | {
        label: string;
        url: string;
        target?: ('_self' | '_blank') | null;
        /**
         * Optional Lucide icon name
         */
        iconName?: string | null;
        /**
         * Add nested links to create a dropdown menu.
         */
        children?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  callToAction: {
    label: string;
    url: string;
    target?: ('_self' | '_blank') | null;
    style?: ('primary' | 'secondary' | 'accent' | 'neutral' | 'ghost' | 'outline' | 'link') | null;
    size?: ('sm' | 'md' | 'lg') | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Optional DaisyUI theme name for the footer (e.g., "dark" or "neutral")
   */
  themeOverride?: string | null;
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              url: string;
              target?: ('_self' | '_blank') | null;
              /**
               * Optional Lucide icon name
               */
              iconName?: string | null;
              /**
               * Add nested links to create a dropdown menu.
               */
              children?:
                | {
                    label: string;
                    url: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform?: ('facebook' | 'twitter' | 'instagram' | 'linkedin' | 'youtube' | 'github' | 'custom') | null;
        url: string;
        /**
         * Optional Lucide icon name
         */
        iconOverride?: string | null;
        id?: string | null;
      }[]
    | null;
  legalText: string;
  /**
   * Links for Privacy Policy, Terms of Service, etc.
   */
  bottomLinks?:
    | {
        label: string;
        url: string;
        target?: ('_self' | '_blank') | null;
        /**
         * Optional Lucide icon name
         */
        iconName?: string | null;
        /**
         * Add nested links to create a dropdown menu.
         */
        children?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "identity_select".
 */
export interface IdentitySelect<T extends boolean = true> {
  siteName?: T;
  logoLight?: T;
  logoDark?: T;
  favicon?: T;
  logoSize?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme_select".
 */
export interface ThemeSelect<T extends boolean = true> {
  defaultTheme?: T;
  fonts?:
    | T
    | {
        sans?: T;
        heading?: T;
      };
  structure?:
    | T
    | {
        radiusBox?: T;
        radiusField?: T;
        radiusSelector?: T;
        borderSize?: T;
        depth?: T;
        noise?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  isSticky?: T;
  themeOverride?: T;
  navigation?:
    | T
    | {
        label?: T;
        url?: T;
        target?: T;
        iconName?: T;
        children?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  callToAction?:
    | T
    | {
        label?: T;
        url?: T;
        target?: T;
        style?: T;
        size?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  themeOverride?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              target?: T;
              iconName?: T;
              children?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        iconOverride?: T;
        id?: T;
      };
  legalText?: T;
  bottomLinks?:
    | T
    | {
        label?: T;
        url?: T;
        target?: T;
        iconName?: T;
        children?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}