/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    media: Media;
    licenses: License;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    licenses: LicensesSelect<false> | LicensesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    identity: Identity;
    theme: Theme;
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    identity: IdentitySelect<false> | IdentitySelect<true>;
    theme: ThemeSelect<false> | ThemeSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Internal reference title for this page (e.g., "Home Page").
   */
  title: string;
  blocks: (
    | HeroBlockType
    | FeatureGridBlockType
    | TestimonialBlockType
    | PricingBlockType
    | ServicesBlockType
    | ContactBlockType
    | ValuePropositionBlockType
    | AboutBlockType
    | ServiceAreaBlockType
    | QuoteFunnelBlockType
  )[];
  /**
   * The URL path. Use "home" for the root index (/).
   */
  slug: string;
  seo: {
    /**
     * The title tag shown in search engines and browser tabs.
     */
    title: string;
    /**
     * The meta description shown in search engine results.
     */
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlockType".
 */
export interface HeroBlockType {
  /**
   * Choose the visual layout for this hero section.
   */
  variant?: ('standard' | 'split' | 'cinematic') | null;
  badge?: {
    label?: string | null;
    color?: ('primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error') | null;
    size?: ('xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    isOutline?: boolean | null;
  };
  heading: string;
  subheading?: string | null;
  actions?:
    | {
        link: {
          label: string;
          url: string;
          target?: ('_self' | '_blank') | null;
          style?: ('primary' | 'secondary' | 'accent' | 'neutral' | 'ghost' | 'outline' | 'link') | null;
          size?: ('sm' | 'md' | 'lg') | null;
        };
        id?: string | null;
      }[]
    | null;
  media?: (number | null) | Media;
  mediaPosition?: ('left' | 'right') | null;
  /**
   * Optional. Define a unique ID for this block to enable deep-linking (e.g., entering "services" here allows linking to "#services"). Do not include the # symbol.
   */
  anchorId?: string | null;
  /**
   * Optional DaisyUI theme specifically for this section.
   */
  themeOverride?:
    | (
        | 'agency-default'
        | 'light'
        | 'cupcake'
        | 'bumblebee'
        | 'emerald'
        | 'corporate'
        | 'retro'
        | 'cyberpunk'
        | 'valentine'
        | 'garden'
        | 'aqua'
        | 'lofi'
        | 'pastel'
        | 'fantasy'
        | 'wireframe'
        | 'cmyk'
        | 'autumn'
        | 'acid'
        | 'lemonade'
        | 'winter'
        | 'nord'
        | 'dark'
        | 'synthwave'
        | 'halloween'
        | 'forest'
        | 'black'
        | 'luxury'
        | 'dracula'
        | 'business'
        | 'night'
        | 'coffee'
        | 'dim'
        | 'sunset'
      )
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'HeroBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Screen reader text. Crucial for SEO and Accessibility.
   */
  altText: string;
  /**
   * Optional base64 blurhash string for instant loading states.
   */
  blurhash?: string | null;
  /**
   * Object-position X percentage (0-100)
   */
  focalPointX?: number | null;
  /**
   * Object-position Y percentage (0-100)
   */
  focalPointY?: number | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlockType".
 */
export interface FeatureGridBlockType {
  /**
   * Choose the visual layout for this feature grid.
   */
  variant?: 'standard' | null;
  heading?: string | null;
  columns?: number | null;
  subheading?: string | null;
  alignment?: ('left' | 'center' | 'right') | null;
  features: {
    title: string;
    description: string;
    icon: {
      type?: ('lucide' | 'svg-string' | 'image') | null;
      /**
       * Enter the Lucide icon name, paste raw SVG, or provide an image URL based on the type selected.
       */
      value: string;
    };
    link: {
      label: string;
      url: string;
      target?: ('_self' | '_blank') | null;
      style?: ('primary' | 'secondary' | 'accent' | 'neutral' | 'ghost' | 'outline' | 'link') | null;
      size?: ('sm' | 'md' | 'lg') | null;
    };
    id?: string | null;
  }[];
  /**
   * Optional. Define a unique ID for this block to enable deep-linking (e.g., entering "services" here allows linking to "#services"). Do not include the # symbol.
   */
  anchorId?: string | null;
  /**
   * Optional DaisyUI theme specifically for this section.
   */
  themeOverride?:
    | (
        | 'agency-default'
        | 'light'
        | 'cupcake'
        | 'bumblebee'
        | 'emerald'
        | 'corporate'
        | 'retro'
        | 'cyberpunk'
        | 'valentine'
        | 'garden'
        | 'aqua'
        | 'lofi'
        | 'pastel'
        | 'fantasy'
        | 'wireframe'
        | 'cmyk'
        | 'autumn'
        | 'acid'
        | 'lemonade'
        | 'winter'
        | 'nord'
        | 'dark'
        | 'synthwave'
        | 'halloween'
        | 'forest'
        | 'black'
        | 'luxury'
        | 'dracula'
        | 'business'
        | 'night'
        | 'coffee'
        | 'dim'
        | 'sunset'
      )
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'FeatureGridBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialBlockType".
 */
export interface TestimonialBlockType {
  /**
   * Choose the visual layout for this block.
   */
  variant?: ('grid' | 'slider' | 'featured') | null;
  heading?: string | null;
  testimonials: {
    quote: string;
    authorName: string;
    authorRole?: string | null;
    authorCompany?: string | null;
    authorImage?: (number | null) | Media;
    rating?: number | null;
    id?: string | null;
  }[];
  /**
   * Optional. Define a unique ID for this block to enable deep-linking (e.g., entering "services" here allows linking to "#services"). Do not include the # symbol.
   */
  anchorId?: string | null;
  /**
   * Optional DaisyUI theme specifically for this section.
   */
  themeOverride?:
    | (
        | 'agency-default'
        | 'light'
        | 'cupcake'
        | 'bumblebee'
        | 'emerald'
        | 'corporate'
        | 'retro'
        | 'cyberpunk'
        | 'valentine'
        | 'garden'
        | 'aqua'
        | 'lofi'
        | 'pastel'
        | 'fantasy'
        | 'wireframe'
        | 'cmyk'
        | 'autumn'
        | 'acid'
        | 'lemonade'
        | 'winter'
        | 'nord'
        | 'dark'
        | 'synthwave'
        | 'halloween'
        | 'forest'
        | 'black'
        | 'luxury'
        | 'dracula'
        | 'business'
        | 'night'
        | 'coffee'
        | 'dim'
        | 'sunset'
      )
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'TestimonialBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingBlockType".
 */
export interface PricingBlockType {
  /**
   * Choose the visual layout for this pricing section.
   */
  variant?: 'cards' | null;
  heading?: string | null;
  subheading?: string | null;
  tiers: {
    name: string;
    price: string;
    billingPeriod?: string | null;
    description?: string | null;
    features?:
      | {
          feature: string;
          id?: string | null;
        }[]
      | null;
    isHighlighted?: boolean | null;
    badge?: {
      label?: string | null;
      color?: ('primary' | 'secondary' | 'accent' | 'neutral' | 'info' | 'success' | 'warning' | 'error') | null;
      size?: ('xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
      isOutline?: boolean | null;
    };
    link: {
      label: string;
      url: string;
      target?: ('_self' | '_blank') | null;
      style?: ('primary' | 'secondary' | 'accent' | 'neutral' | 'ghost' | 'outline' | 'link') | null;
      size?: ('sm' | 'md' | 'lg') | null;
    };
    id?: string | null;
  }[];
  /**
   * Optional. Define a unique ID for this block to enable deep-linking (e.g., entering "services" here allows linking to "#services"). Do not include the # symbol.
   */
  anchorId?: string | null;
  /**
   * Optional DaisyUI theme specifically for this section.
   */
  themeOverride?:
    | (
        | 'agency-default'
        | 'light'
        | 'cupcake'
        | 'bumblebee'
        | 'emerald'
        | 'corporate'
        | 'retro'
        | 'cyberpunk'
        | 'valentine'
        | 'garden'
        | 'aqua'
        | 'lofi'
        | 'pastel'
        | 'fantasy'
        | 'wireframe'
        | 'cmyk'
        | 'autumn'
        | 'acid'
        | 'lemonade'
        | 'winter'
        | 'nord'
        | 'dark'
        | 'synthwave'
        | 'halloween'
        | 'forest'
        | 'black'
        | 'luxury'
        | 'dracula'
        | 'business'
        | 'night'
        | 'coffee'
        | 'dim'
        | 'sunset'
      )
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'PricingBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesBlockType".
 */
export interface ServicesBlockType {
  /**
   * Choose the visual layout for this services section.
   */
  variant?: 'list' | null;
  heading?: string | null;
  subheading?: string | null;
  services: {
    title: string;
    price?: string | null;
    description: string;
    icon: {
      type?: ('lucide' | 'svg-string' | 'image') | null;
      /**
       * Enter the Lucide icon name, paste raw SVG, or provide an image URL based on the type selected.
       */
      value: string;
    };
    media?: (number | null) | Media;
    link: {
      label: string;
      url: string;
      target?: ('_self' | '_blank') | null;
      style?: ('primary' | 'secondary' | 'accent' | 'neutral' | 'ghost' | 'outline' | 'link') | null;
      size?: ('sm' | 'md' | 'lg') | null;
    };
    id?: string | null;
  }[];
  /**
   * Optional. Define a unique ID for this block to enable deep-linking (e.g., entering "services" here allows linking to "#services"). Do not include the # symbol.
   */
  anchorId?: string | null;
  /**
   * Optional DaisyUI theme specifically for this section.
   */
  themeOverride?:
    | (
        | 'agency-default'
        | 'light'
        | 'cupcake'
        | 'bumblebee'
        | 'emerald'
        | 'corporate'
        | 'retro'
        | 'cyberpunk'
        | 'valentine'
        | 'garden'
        | 'aqua'
        | 'lofi'
        | 'pastel'
        | 'fantasy'
        | 'wireframe'
        | 'cmyk'
        | 'autumn'
        | 'acid'
        | 'lemonade'
        | 'winter'
        | 'nord'
        | 'dark'
        | 'synthwave'
        | 'halloween'
        | 'forest'
        | 'black'
        | 'luxury'
        | 'dracula'
        | 'business'
        | 'night'
        | 'coffee'
        | 'dim'
        | 'sunset'
      )
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ServicesBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlockType".
 */
export interface ContactBlockType {
  /**
   * Choose the visual layout for this contact section.
   */
  variant?: 'standard' | null;
  heading: string;
  subheading?: string | null;
  email?: string | null;
  phone?: string | null;
  address?: string | null;
  /**
   * Toggle the standard contact form visibility.
   */
  showForm?: boolean | null;
  /**
   * Optional. Define a unique ID for this block to enable deep-linking (e.g., entering "services" here allows linking to "#services"). Do not include the # symbol.
   */
  anchorId?: string | null;
  /**
   * Optional DaisyUI theme specifically for this section.
   */
  themeOverride?:
    | (
        | 'agency-default'
        | 'light'
        | 'cupcake'
        | 'bumblebee'
        | 'emerald'
        | 'corporate'
        | 'retro'
        | 'cyberpunk'
        | 'valentine'
        | 'garden'
        | 'aqua'
        | 'lofi'
        | 'pastel'
        | 'fantasy'
        | 'wireframe'
        | 'cmyk'
        | 'autumn'
        | 'acid'
        | 'lemonade'
        | 'winter'
        | 'nord'
        | 'dark'
        | 'synthwave'
        | 'halloween'
        | 'forest'
        | 'black'
        | 'luxury'
        | 'dracula'
        | 'business'
        | 'night'
        | 'coffee'
        | 'dim'
        | 'sunset'
      )
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ContactBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ValuePropositionBlockType".
 */
export interface ValuePropositionBlockType {
  /**
   * Choose the visual layout for this value proposition section.
   */
  variant?: 'standard' | null;
  heading: string;
  subheading?: string | null;
  propositions: {
    title: string;
    description: string;
    icon: {
      type?: ('lucide' | 'svg-string' | 'image') | null;
      /**
       * Enter the Lucide icon name, paste raw SVG, or provide an image URL based on the type selected.
       */
      value: string;
    };
    id?: string | null;
  }[];
  /**
   * Optional. Define a unique ID for this block to enable deep-linking (e.g., entering "services" here allows linking to "#services"). Do not include the # symbol.
   */
  anchorId?: string | null;
  /**
   * Optional DaisyUI theme specifically for this section.
   */
  themeOverride?:
    | (
        | 'agency-default'
        | 'light'
        | 'cupcake'
        | 'bumblebee'
        | 'emerald'
        | 'corporate'
        | 'retro'
        | 'cyberpunk'
        | 'valentine'
        | 'garden'
        | 'aqua'
        | 'lofi'
        | 'pastel'
        | 'fantasy'
        | 'wireframe'
        | 'cmyk'
        | 'autumn'
        | 'acid'
        | 'lemonade'
        | 'winter'
        | 'nord'
        | 'dark'
        | 'synthwave'
        | 'halloween'
        | 'forest'
        | 'black'
        | 'luxury'
        | 'dracula'
        | 'business'
        | 'night'
        | 'coffee'
        | 'dim'
        | 'sunset'
      )
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ValuePropositionBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutBlockType".
 */
export interface AboutBlockType {
  /**
   * Choose the visual layout for this about section.
   */
  variant?: 'standard' | null;
  heading: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * An optional image to display next to the about block content.
   */
  media?: (number | null) | Media;
  mediaPosition?: ('left' | 'right') | null;
  /**
   * Optional. Define a unique ID for this block to enable deep-linking (e.g., entering "services" here allows linking to "#services"). Do not include the # symbol.
   */
  anchorId?: string | null;
  /**
   * Optional DaisyUI theme specifically for this section.
   */
  themeOverride?:
    | (
        | 'agency-default'
        | 'light'
        | 'cupcake'
        | 'bumblebee'
        | 'emerald'
        | 'corporate'
        | 'retro'
        | 'cyberpunk'
        | 'valentine'
        | 'garden'
        | 'aqua'
        | 'lofi'
        | 'pastel'
        | 'fantasy'
        | 'wireframe'
        | 'cmyk'
        | 'autumn'
        | 'acid'
        | 'lemonade'
        | 'winter'
        | 'nord'
        | 'dark'
        | 'synthwave'
        | 'halloween'
        | 'forest'
        | 'black'
        | 'luxury'
        | 'dracula'
        | 'business'
        | 'night'
        | 'coffee'
        | 'dim'
        | 'sunset'
      )
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'AboutBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServiceAreaBlockType".
 */
export interface ServiceAreaBlockType {
  /**
   * Choose the visual layout for the service area section.
   */
  variant?: 'standard' | null;
  heading: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Provide a Google Maps Embed URL (e.g., https://www.google.com/maps/embed?pb=...).
   */
  mapEmbedUrl: string;
  /**
   * Optional. Define a unique ID for this block to enable deep-linking (e.g., entering "services" here allows linking to "#services"). Do not include the # symbol.
   */
  anchorId?: string | null;
  /**
   * Optional DaisyUI theme specifically for this section.
   */
  themeOverride?:
    | (
        | 'agency-default'
        | 'light'
        | 'cupcake'
        | 'bumblebee'
        | 'emerald'
        | 'corporate'
        | 'retro'
        | 'cyberpunk'
        | 'valentine'
        | 'garden'
        | 'aqua'
        | 'lofi'
        | 'pastel'
        | 'fantasy'
        | 'wireframe'
        | 'cmyk'
        | 'autumn'
        | 'acid'
        | 'lemonade'
        | 'winter'
        | 'nord'
        | 'dark'
        | 'synthwave'
        | 'halloween'
        | 'forest'
        | 'black'
        | 'luxury'
        | 'dracula'
        | 'business'
        | 'night'
        | 'coffee'
        | 'dim'
        | 'sunset'
      )
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ServiceAreaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuoteFunnelBlockType".
 */
export interface QuoteFunnelBlockType {
  /**
   * Choose the visual layout for this quote funnel.
   */
  variant?: 'standard' | null;
  heading: string;
  subheading?: string | null;
  steps: {
    question: string;
    fieldType: 'text' | 'email' | 'number' | 'select' | 'radio';
    options?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  /**
   * Message to show after the user successfully completes the funnel.
   */
  successMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional webhook URL to submit the lead data to (e.g. Zapier or Make.com).
   */
  webhookUrl?: string | null;
  /**
   * Optional. Define a unique ID for this block to enable deep-linking (e.g., entering "services" here allows linking to "#services"). Do not include the # symbol.
   */
  anchorId?: string | null;
  /**
   * Optional DaisyUI theme specifically for this section.
   */
  themeOverride?:
    | (
        | 'agency-default'
        | 'light'
        | 'cupcake'
        | 'bumblebee'
        | 'emerald'
        | 'corporate'
        | 'retro'
        | 'cyberpunk'
        | 'valentine'
        | 'garden'
        | 'aqua'
        | 'lofi'
        | 'pastel'
        | 'fantasy'
        | 'wireframe'
        | 'cmyk'
        | 'autumn'
        | 'acid'
        | 'lemonade'
        | 'winter'
        | 'nord'
        | 'dark'
        | 'synthwave'
        | 'halloween'
        | 'forest'
        | 'black'
        | 'luxury'
        | 'dracula'
        | 'business'
        | 'night'
        | 'coffee'
        | 'dim'
        | 'sunset'
      )
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'QuoteFunnelBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "licenses".
 */
export interface License {
  id: number;
  email: string;
  licenseKey: string;
  status: 'active' | 'expired';
  lemonSqueezyCustomerId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'licenses';
        value: number | License;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  blocks?:
    | T
    | {
        HeroBlock?: T | HeroBlockTypeSelect<T>;
        FeatureGridBlock?: T | FeatureGridBlockTypeSelect<T>;
        TestimonialBlock?: T | TestimonialBlockTypeSelect<T>;
        PricingBlock?: T | PricingBlockTypeSelect<T>;
        ServicesBlock?: T | ServicesBlockTypeSelect<T>;
        ContactBlock?: T | ContactBlockTypeSelect<T>;
        ValuePropositionBlock?: T | ValuePropositionBlockTypeSelect<T>;
        AboutBlock?: T | AboutBlockTypeSelect<T>;
        ServiceAreaBlock?: T | ServiceAreaBlockTypeSelect<T>;
        QuoteFunnelBlock?: T | QuoteFunnelBlockTypeSelect<T>;
      };
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlockType_select".
 */
export interface HeroBlockTypeSelect<T extends boolean = true> {
  variant?: T;
  badge?:
    | T
    | {
        label?: T;
        color?: T;
        size?: T;
        isOutline?: T;
      };
  heading?: T;
  subheading?: T;
  actions?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              url?: T;
              target?: T;
              style?: T;
              size?: T;
            };
        id?: T;
      };
  media?: T;
  mediaPosition?: T;
  anchorId?: T;
  themeOverride?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlockType_select".
 */
export interface FeatureGridBlockTypeSelect<T extends boolean = true> {
  variant?: T;
  heading?: T;
  columns?: T;
  subheading?: T;
  alignment?: T;
  features?:
    | T
    | {
        title?: T;
        description?: T;
        icon?:
          | T
          | {
              type?: T;
              value?: T;
            };
        link?:
          | T
          | {
              label?: T;
              url?: T;
              target?: T;
              style?: T;
              size?: T;
            };
        id?: T;
      };
  anchorId?: T;
  themeOverride?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialBlockType_select".
 */
export interface TestimonialBlockTypeSelect<T extends boolean = true> {
  variant?: T;
  heading?: T;
  testimonials?:
    | T
    | {
        quote?: T;
        authorName?: T;
        authorRole?: T;
        authorCompany?: T;
        authorImage?: T;
        rating?: T;
        id?: T;
      };
  anchorId?: T;
  themeOverride?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingBlockType_select".
 */
export interface PricingBlockTypeSelect<T extends boolean = true> {
  variant?: T;
  heading?: T;
  subheading?: T;
  tiers?:
    | T
    | {
        name?: T;
        price?: T;
        billingPeriod?: T;
        description?: T;
        features?:
          | T
          | {
              feature?: T;
              id?: T;
            };
        isHighlighted?: T;
        badge?:
          | T
          | {
              label?: T;
              color?: T;
              size?: T;
              isOutline?: T;
            };
        link?:
          | T
          | {
              label?: T;
              url?: T;
              target?: T;
              style?: T;
              size?: T;
            };
        id?: T;
      };
  anchorId?: T;
  themeOverride?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesBlockType_select".
 */
export interface ServicesBlockTypeSelect<T extends boolean = true> {
  variant?: T;
  heading?: T;
  subheading?: T;
  services?:
    | T
    | {
        title?: T;
        price?: T;
        description?: T;
        icon?:
          | T
          | {
              type?: T;
              value?: T;
            };
        media?: T;
        link?:
          | T
          | {
              label?: T;
              url?: T;
              target?: T;
              style?: T;
              size?: T;
            };
        id?: T;
      };
  anchorId?: T;
  themeOverride?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlockType_select".
 */
export interface ContactBlockTypeSelect<T extends boolean = true> {
  variant?: T;
  heading?: T;
  subheading?: T;
  email?: T;
  phone?: T;
  address?: T;
  showForm?: T;
  anchorId?: T;
  themeOverride?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ValuePropositionBlockType_select".
 */
export interface ValuePropositionBlockTypeSelect<T extends boolean = true> {
  variant?: T;
  heading?: T;
  subheading?: T;
  propositions?:
    | T
    | {
        title?: T;
        description?: T;
        icon?:
          | T
          | {
              type?: T;
              value?: T;
            };
        id?: T;
      };
  anchorId?: T;
  themeOverride?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutBlockType_select".
 */
export interface AboutBlockTypeSelect<T extends boolean = true> {
  variant?: T;
  heading?: T;
  content?: T;
  media?: T;
  mediaPosition?: T;
  anchorId?: T;
  themeOverride?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServiceAreaBlockType_select".
 */
export interface ServiceAreaBlockTypeSelect<T extends boolean = true> {
  variant?: T;
  heading?: T;
  content?: T;
  mapEmbedUrl?: T;
  anchorId?: T;
  themeOverride?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuoteFunnelBlockType_select".
 */
export interface QuoteFunnelBlockTypeSelect<T extends boolean = true> {
  variant?: T;
  heading?: T;
  subheading?: T;
  steps?:
    | T
    | {
        question?: T;
        fieldType?: T;
        options?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        id?: T;
      };
  successMessage?: T;
  webhookUrl?: T;
  anchorId?: T;
  themeOverride?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  altText?: T;
  blurhash?: T;
  focalPointX?: T;
  focalPointY?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "licenses_select".
 */
export interface LicensesSelect<T extends boolean = true> {
  email?: T;
  licenseKey?: T;
  status?: T;
  lemonSqueezyCustomerId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "identity".
 */
export interface Identity {
  id: number;
  siteName: string;
  logoLight?: (number | null) | Media;
  logoDark?: (number | null) | Media;
  favicon?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme".
 */
export interface Theme {
  id: number;
  /**
   * The fallback DaisyUI theme for the entire website.
   */
  defaultTheme:
    | 'agency-default'
    | 'light'
    | 'cupcake'
    | 'bumblebee'
    | 'emerald'
    | 'corporate'
    | 'retro'
    | 'cyberpunk'
    | 'valentine'
    | 'garden'
    | 'aqua'
    | 'lofi'
    | 'pastel'
    | 'fantasy'
    | 'wireframe'
    | 'cmyk'
    | 'autumn'
    | 'acid'
    | 'lemonade'
    | 'winter'
    | 'nord'
    | 'dark'
    | 'synthwave'
    | 'halloween'
    | 'forest'
    | 'black'
    | 'luxury'
    | 'dracula'
    | 'business'
    | 'night'
    | 'coffee'
    | 'dim'
    | 'sunset';
  fonts: {
    /**
     * Google Font name for standard text.
     */
    sans: string;
    /**
     * Google Font name for headings.
     */
    heading: string;
  };
  structure: {
    radiusBox: string;
    radiusField: string;
    radiusSelector: string;
    borderSize: string;
    depth?: ('0' | '1') | null;
    noise?: ('0' | '1') | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  isSticky?: boolean | null;
  /**
   * Optional DaisyUI theme name for the header (e.g., "dark")
   */
  themeOverride?: string | null;
  navigation?:
    | {
        label: string;
        url: string;
        target?: ('_self' | '_blank') | null;
        /**
         * Optional Lucide icon name
         */
        iconName?: string | null;
        /**
         * Add nested links to create a dropdown menu.
         */
        children?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  callToAction: {
    label: string;
    url: string;
    target?: ('_self' | '_blank') | null;
    style?: ('primary' | 'secondary' | 'accent' | 'neutral' | 'ghost' | 'outline' | 'link') | null;
    size?: ('sm' | 'md' | 'lg') | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Optional DaisyUI theme name for the footer (e.g., "dark" or "neutral")
   */
  themeOverride?: string | null;
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              url: string;
              target?: ('_self' | '_blank') | null;
              /**
               * Optional Lucide icon name
               */
              iconName?: string | null;
              /**
               * Add nested links to create a dropdown menu.
               */
              children?:
                | {
                    label: string;
                    url: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform?: ('facebook' | 'twitter' | 'instagram' | 'linkedin' | 'youtube' | 'github' | 'custom') | null;
        url: string;
        /**
         * Optional Lucide icon name
         */
        iconOverride?: string | null;
        id?: string | null;
      }[]
    | null;
  legalText: string;
  /**
   * Links for Privacy Policy, Terms of Service, etc.
   */
  bottomLinks?:
    | {
        label: string;
        url: string;
        target?: ('_self' | '_blank') | null;
        /**
         * Optional Lucide icon name
         */
        iconName?: string | null;
        /**
         * Add nested links to create a dropdown menu.
         */
        children?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "identity_select".
 */
export interface IdentitySelect<T extends boolean = true> {
  siteName?: T;
  logoLight?: T;
  logoDark?: T;
  favicon?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme_select".
 */
export interface ThemeSelect<T extends boolean = true> {
  defaultTheme?: T;
  fonts?:
    | T
    | {
        sans?: T;
        heading?: T;
      };
  structure?:
    | T
    | {
        radiusBox?: T;
        radiusField?: T;
        radiusSelector?: T;
        borderSize?: T;
        depth?: T;
        noise?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  isSticky?: T;
  themeOverride?: T;
  navigation?:
    | T
    | {
        label?: T;
        url?: T;
        target?: T;
        iconName?: T;
        children?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  callToAction?:
    | T
    | {
        label?: T;
        url?: T;
        target?: T;
        style?: T;
        size?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  themeOverride?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              target?: T;
              iconName?: T;
              children?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        iconOverride?: T;
        id?: T;
      };
  legalText?: T;
  bottomLinks?:
    | T
    | {
        label?: T;
        url?: T;
        target?: T;
        iconName?: T;
        children?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}